name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20']
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup FirebirdSQL container
      uses: juarezr/firebirdsql-github-action@v1.2.0
      with:
        version: '4.0'
        isc_password: "masterkey"

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
